apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-e-portal-api-service-test
  labels:
    environment: test
  annotations:
    run.googleapis.com/cloudsql-instances: test-e-portal-api-service:asia-south2:test-e-portal-db-test

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cloudsql-instances: test-e-portal-api-service:asia-south2:test-e-portal-db-test
    spec:
      containerConcurrency: 80
      containers:
        - image: asia-south2-docker.pkg.dev/test-e-portal-api-service/test-e-portal-images/test-e-portal-api-service:TAG_PLACEHOLDER
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
            - name: ENV
              value: test
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: test-db-url
                  key: latest
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: test-db-username
                  key: latest
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-db-password
                  key: latest
          resources:
            limits:
              cpu: '1'
              memory: 512Mi  # Increased from 256Mi to 512Mi
